### PR TITLE
Change Lobby Display

### PR DESCRIPTION
**Pull request by raw-chicken**
Change lobby display so that it'll display as two rows instead of sometimes changing to one long row of 10 champions.

### CODE REVIEW

**Comment by raw-chicken** [comment]
Made it so that if you are looking at settings and click profile/lobby, then the settings will close.

**Comment by raw-chicken** [comment]
When Lytical is waiting for a response in lobby, it will display "Loading..." so that it's not just a blank screen. (No animation tho)

**Comment by raw-chicken** [comment]
- Added the loading animation for the Lobby
- Formatted some of the code to keep code consistent (at 2 space indents)
- Clicking anywhere in MatchHistoryItem will open details (other than clicking on the champion, which will open champ page)

**Comment by downthecrop** [comment]
I should break out the loading dots into a component. Good changes. Thank you!

**Pull request merged**
